apiVersion: v1
kind: Service
metadata:
  name: gestao-pedidos-payment-service-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: gestao-pedidos-payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: port1
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: port2
  type: LoadBalancer