apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestao-pedidos-payment
  labels:
    app: gestao-pedidos-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestao-pedidos-payment
  template:
    metadata:
      labels:
        app: gestao-pedidos-payment
    spec:
      containers:
        - name: gestao-pedidos-payment
          image: gestaopedidospayment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: WebHookUrl
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: WEBHOOK_URL
            - name: MongoConnectionString
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MONGODB_CONNECTION_STRING
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"